meta_product_name: "Fademe"
meta_title: "Fademe"
meta_description: "Fademe is a Flutter application. A weed diary app. Smoke too much weed? Smoke too little? Spending too much on weed? Find out with Fademe.

Document your cannabis use with a tap. Record what, when, where, how much, or even take a selfie with your bud.

Note: Flutter application means it will release for both Android and iOS phones.

Hashtags: Flutter, Flutter app, Fademe, fade me, fade me bro, cannabis diary, cannabis log, cannabis connoisseur, cannabis aficionado, weed log, smoking documentation, marijuana log, weed application, weed connoisseur, weed aficionado, weed, cannabis, smoking"
  